Exercise 1: Decision Tree

In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings 
from sklearn.metrics import accuracy_score, classification_report
warnings.filterwarnings("ignore")

In [8]:
user = pd.read_csv("users.csv")

In [9]:
user.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   12            19000          0
1  15810944    Male   11            20000          0
2  15668575  Female    1            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   10            76000          0

In [10]:
user['Purchased'].unique()

array([0, 1])

In [11]:
user['Gender'].unique()

<StringArray>
['Male', 'Female']
Length: 2, dtype: str

In [12]:
user['Age'].min()

np.int64(1)

In [13]:
user['Age'].max()

np.int64(64)

In [14]:
X = user.columns.drop("Purchased")
y = user["Purchased"]

In [15]:
user

     User ID  Gender  Age  EstimatedSalary  Purchased
0   15624510    Male   12            19000          0
1   15810944    Male   11            20000          0
2   15668575  Female    1            43000          0
3   15603246  Female   27            57000          0
4   15804002    Male   10            76000          0
..       ...     ...  ...              ...        ...
94  15786993  Female   45            83000          0
95  15709441  Female   35            44000          0
96  15710257  Female    4            25000          0
97  15582492    Male    5           123000          1
98  15575694    Male   35            73000          0

[99 rows x 5 columns]

In [16]:
user_encoded = pd.get_dummies(user[X]).astype(int)

In [17]:
user_encoded

     User ID  Age  EstimatedSalary  Gender_Female  Gender_Male
0   15624510   12            19000              0            1
1   15810944   11            20000              0            1
2   15668575    1            43000              1            0
3   15603246   27            57000              1            0
4   15804002   10            76000              0            1
..       ...  ...              ...            ...          ...
94  15786993   45            83000              1            0
95  15709441   35            44000              1            0
96  15710257    4            25000              1            0
97  15582492    5           123000              0            1
98  15575694   35            73000              0            1

[99 rows x 5 columns]

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    user_encoded, y, test_size=0.15, random_state=0)
print("Shape of X_train and y_train:", X_train.shape,"and", y_train.shape, "respectively")
print("Shape of X_test and y_test:", X_test.shape,"and", y_test.shape, "respectively")

Shape of X_train and y_train: (84, 5) and (84,) respectively
Shape of X_test and y_test: (15, 5) and (15,) respectively

In [19]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(criterion='gini', random_state=0)
model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=0)

In [20]:
train_predictions = model.predict(X_train)
test_predictions = model.predict(X_test)

In [21]:
pip install export_graphviz

Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement export_graphviz (from versions: none)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for export_graphviz

In [22]:
from sklearn.tree import export_graphviz
import graphviz
data = export_graphviz(model, out_file=None, feature_names=user_encoded.columns)
graph = graphviz.Source(data)
graph

ModuleNotFoundError: No module named 'graphviz'

In [23]:
spam_data = pd.read_csv("spambase.csv")

In [24]:
spam_data.head()

,word_freq_make,word_freq_address,word_freq_all,word_freq_3d,word_req_our,word_freq_over,word_freq_remove,word_freq_internet,word_freq_order,word_freq_mail,...,char_freq_;,char_freq_(,char_freq_[,char_freq_!,char_freq_$,char_freq_#,capital_run_length_average,capital_run_length_longest,capital_run_length_total,spam
0,0.00,0.64,0.64,0.0,0.32,0.00,0.00,0.00,0.00,0.00,...,0.00,0.000,0.0,0.778,0.000,0.000,3.756,61,278,1
1,0.21,0.28,0.50,0.0,0.14,0.28,0.21,0.07,0.00,0.94,...,0.00,0.132,0.0,0.372,0.180,0.048,5.114,101,1028,1
2,0.06,0.00,0.71,0.0,1.23,0.19,0.19,0.12,0.64,0.25,...,0.01,0.143,0.0,0.276,0.184,0.010,9.821,485,2259,1
3,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.00,0.137,0.0,0.137,0.000,0.000,3.537,40,191,1
4,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.00,0.135,0.0,0.135,0.000,0.000,3.537,40,191,1

In [25]:
spam_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 4601 entries, 0 to 4600
Data columns (total 58 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   word_freq_make              4601 non-null   float64
 1   word_freq_address           4601 non-null   float64
 2   word_freq_all               4601 non-null   float64
 3   word_freq_3d                4601 non-null   float64
 4   word_req_our                4601 non-null   float64
 5   word_freq_over              4601 non-null   float64
 6   word_freq_remove            4601 non-null   float64
 7   word_freq_internet          4601 non-null   float64
 8   word_freq_order             4601 non-null   float64
 9   word_freq_mail              4601 non-null   float64
 10  word_freq_receive           4601 non-null   float64
 11  word_freq_will              4601 non-null   float64
 12  word_freq_people            4601 non-null   float64
 13  word_freq_report            4601 non-null   float64
 14  word_freq_addresses         4601 non-null   float64
 15  word_freq_free              4601 non-null   float64
 16  word_freq_business          4601 non-null   float64
 17  word_freq_email             4601 non-null   float64
 18  word_freq_you               4601 non-null   float64
 19  word_freq_credit            4601 non-null   float64
 20  word_freq_your              4601 non-null   float64
 21  word_freq_font              4601 non-null   float64
 22  word_freq_000               4601 non-null   float64
 23  word_freq_money             4601 non-null   float64
 24  word_freq_hp                4601 non-null   float64
 25  word_freq_hpl               4601 non-null   float64
 26  word_freq_george            4601 non-null   float64
 27  word_freq_650               4601 non-null   float64
 28  word_freq_lab               4601 non-null   float64
 29  word_freq_labs              4601 non-null   float64
 30  word_freq_telnet            4601 non-null   float64
 31  word_freq_857               4601 non-null   float64
 32  word_freq_data              4601 non-null   float64
 33  word_freq_415               4601 non-null   float64
 34  word_freq_85                4601 non-null   float64
 35  word_freq_technology        4601 non-null   float64
 36  word_freq_1999              4601 non-null   float64
 37  word_freq_parts             4601 non-null   float64
 38  word_freq_pm                4601 non-null   float64
 39  word_freq_direct            4601 non-null   float64
 40  word_freq_cs                4601 non-null   float64
 41  word_freq_meeting           4601 non-null   float64
 42  word_freq_original          4601 non-null   float64
 43  word_freq_project           4601 non-null   float64
 44  word_freq_re                4601 non-null   float64
 45  word_freq_edu               4601 non-null   float64
 46  word_freq_table             4601 non-null   float64
 47  word_freq_conference        4601 non-null   float64
 48  char_freq_;                 4601 non-null   float64
 49  char_freq_(                 4601 non-null   float64
 50  char_freq_[                 4601 non-null   float64
 51  char_freq_!                 4601 non-null   float64
 52  char_freq_$                 4601 non-null   float64
 53  char_freq_#                 4601 non-null   float64
 54  capital_run_length_average  4601 non-null   float64
 55  capital_run_length_longest  4601 non-null   int64
 56  capital_run_length_total    4601 non-null   int64
 57  spam                        4601 non-null   int64
dtypes: float64(55), int64(3)
memory usage: 2.0 MB

In [26]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=100, min_samples_split=20,min_impurity_decrease=0.05)
model.fit(X_train, y_train)
train_accuracy=model.score(X_train, y_train)
test_accuracy=model.score(X_test, y_test)
print(train_accuracy,test_accuracy)

0.8214285714285714 0.7333333333333333

In [28]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier
model=AdaBoostClassifier(n_estimators=100)
model.fit(X_train, y_train)
train_accuracy=model.score(X_train, y_train)
test_accuracy=model.score(X_test, y_test)
print(train_accuracy,test_accuracy)

1.0 0.8666666666666667